# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#######
# General metadata
#######
site_name: Cumbuca Docs
site_url: https://docs.cumbuca.dev
repo_url: http://github.com/cumbucadev/comunidade
site_author: cumbuca.dev
copyright: "2026, cumbuca.dev"
site_description: Documentação oficial da comunidade da Cumbuca Dev

#######
# Theme settings
#######
theme:
  name: material
  logo: assets/img/logo-transparent.png
  favicon: assets/img/logo-transparent.png
  language: pt-BR
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.sections
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: cumbuca-light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - scheme: cumbuca-dark
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Light mode

#######
# Docs settings
#######
nav:
  - Cumbuca Docs:
    - intro/index.md
    - Como contribuir: contribuindo/index.md
    - Código de Conduta: contribuindo/codigo-de-conduta.md
    - Templates:
      - Ata de Reunião: contribuindo/templates/template-ata-reuniao.md
      - Guia do Núcleo: contribuindo/templates/template-nucleo.md

#######
# Development settings
#######
watch:
  - docs

#######
# Docs settings
#######
use_directory_urls: true

#######
# Plugins/extensions settings
#######
plugins:
  - search:
      lang: pt

markdown_extensions:
  - abbr # Abbreviations support
  - attr_list # Attribute lists for elements
  - def_list # Definition lists
  - meta # Metadata support
  - sane_lists # Better handling of lists
  - smarty # Smart punctuation
  - toc: # Table of contents settings
      toc_depth: 2-4
  - pymdownx.emoji: # Emoji support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/css/theme.css
  - assets/css/cards.css

# custom scripts loaded on every page
extra_javascript:
  - assets/js/sidebar.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cumbucadev/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cumbucadev/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@cumbucadev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cumbucadev/
    - icon: fontawesome/solid/paper-plane
      link: mailto:contato@cumbuca.dev
